# Generated by Django 4.1.13 on 2024-06-05 16:47

from django.db import migrations, models
import django.db.models.deletion
import kncc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='enter the player number')),
                ('name', models.CharField(default=None, max_length=40, verbose_name='Enter the player  Name')),
                ('picture', models.ImageField(blank=True, default=None, upload_to=kncc.models.picture, verbose_name='Players Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Enter the Teame  Name')),
                ('logo', models.ImageField(blank=True, default=None, upload_to=kncc.models.picture)),
                ('amount', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='soldout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Enter the amount of player for sold')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kncc.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kncc.team')),
            ],
            options={
                'unique_together': {('team', 'players')},
            },
        ),
    ]
