# Generated by Django 4.1.13 on 2024-06-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kncc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='type',
            field=models.CharField(choices=[('under 19', 'under 19'), ('open', 'open')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='soldout',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kncc.players', verbose_name='Select thae player'),
        ),
        migrations.AlterField(
            model_name='soldout',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kncc.team', verbose_name='Enter the team name '),
        ),
    ]
